from django.urls import path
from deloreports import views


urlpatterns = [
    path('', views.index, name='index'),
    path('auth_login/', views.auth_login, name='auth_login'),
    path('auth_logout/', views.auth_logout, name='auth_logout'),
    path('reports_master_report/', views.reports_master_report, name='reports_master_report'),
    path('district_themes_report/', views.district_themes_report, name='district_themes_report'),
    path('reports_master_report/get_citizen_list', views.get_citizen_list, name='get_citizen_list'),
    path('correspondents_report/', views.correspondents_report, name='correspondents_report'),
    path('correspondents_foiv_report/', views.correspondents_foiv_report, name='correspondents_foiv_report'),
    path('effectiveness_report/', views.effectiveness_report, name='effectiveness_report'),
    path('effectiveness_report/export_excel/',
         views.effectiveness_report_export_excel,
         name='effectiveness_report_export_excel'),
    path('effectiveness_report/get_docs_list', views.get_docs_list, name='get_docs_list'),
    path('effectiveness_report/download_list', views.download_list, name='download_list'),
    path('effectiveness_report/download_docs_list', views.download_docs_list, name='download_docs_list'),
    path('effectiveness_report/get_resolutions_list', views.get_resolutions_list, name='get_resolutions_list'),
    path('effectiveness_quality_report/export_excel/',
         views.effectiveness_quality_report_export_excel,
         name='effectiveness_quality_report_export_excel'),
    path('doc_flow_report/', views.doc_flow_report, name='doc_flow_report'),
    path('paper_flow_report/', views.paper_flow_report, name='paper_flow_report'),
    path('not_assigned_court_documents/', views.not_assigned_court_documents, name='not_assigned_court_documents'),
    path('municipal_legal_act_registration_report/',
         views.municipal_legal_act_registration_report,
         name='municipal_legal_act_registration_report'),
    path('court_documents_report/', views.court_documents_report, name='court_documents_report'),
    path('gov_app_eight_report/', views.gov_app_eight_report, name='gov_app_eight_report'),
    path('prosecutors_reaction_act_report/',
         views.prosecutors_reaction_act_report,
         name='prosecutors_reaction_act_report'),
    path('prosecutors_incoming_docs_report/',
         views.prosecutors_incoming_docs_report,
         name='prosecutors_incoming_docs_report'),
    path('control_cases_report/', views.control_cases_report, name='control_cases_report'),
    path('control_cases_report/get_control_case_docs_list',
         views.get_control_case_docs_list,
         name='get_control_case_docs_list'),
    path('control_cases_report/get_control_case_docs_list2',
         views.get_control_case_docs_list2,
         name='get_control_case_docs_list2'),
    path('control_cases_report/download_list',
         views.download_control_case_docs_list,
         name='download_control_case_docs_list'),
    path('control_cases_report2/', views.control_cases_report2, name='control_cases_report2'),
    path('sstu_export/', views.sstu_export, name='sstu_export'),
    path('sstu_export/download_list/', views.download_arc, name='download_arc'),
    path('sstu_get_protocol/', views.sstu_get_protocol, name='sstu_get_protocol'),
    path('constituency/', views.constituency, name='constituency'),
    path('tos_appeals_report/', views.tos_appeals_report, name='tos_appeals_report'),
    path('tos_appeals_export_excel/', views.tos_appeals_export_excel, name='tos_appeals_export_excel'),
    path('municipal_legal_acts_consideration_report/',
         views.municipal_legal_acts_consideration_report,
         name='municipal_legal_acts_consideration_report'),
    path('municipal_legal_acts_consideration_report/export_excel/',
         views.municipal_legal_acts_consideration_report_export_excel,
         name='municipal_legal_acts_consideration_report_export_excel'),
    path('municipal_legal_acts_consideration_report/get_docs_list',
         views.get_docs_list_municipal_legal_acts_consideration_report,
         name='get_docs_list_municipal_legal_acts_consideration_report'),
    path('municipal_legal_acts_consideration_report/download_list',
         views.download_list_municipal_legal_acts_consideration_report,
         name='download_list_municipal_legal_acts_consideration_report'),
    path('appeals_two_week_period/', views.appeals_two_week_period, name='appeals_two_week_period'),
    path('appeals_two_week_period/export_excel/',
         views.appeals_two_week_period_export_excel,
         name='appeals_two_week_period_export_excel'),
    path('effectiveness_report_betatest/',
         views.effectiveness_report_betatest,
         name='effectiveness_report_betatest'),
    path('effectiveness_report_betatest/export_excel/',
         views.effectiveness_report_export_excel_betatest,
         name='effectiveness_report_export_excel_betatest'),
    path('effectiveness_quality_report_betatest/export_excel/',
         views.effectiveness_quality_report_export_excel_betatest,
         name='effectiveness_quality_report_export_excel_betatest'),
    path('check_documents/', views.check_documents, name='check_documents'),
    path('check_documents/export_word/', views.check_documents_export_word, name='check_documents_export_word'),
    path('editing_resolutions_by_mayor_report/',
         views.editing_resolutions_by_mayor_report,
         name='editing_resolutions_by_mayor_report'),
    path('editing_resolutions_by_mayor_report/export_excel/',
         views.editing_resolutions_by_mayor_report_export_excel,
         name='editing_resolutions_by_mayor_report_export_excel'),
    path('citizens_appeals_json/', views.citizens_appeals_json, name='citizens_appeals_json'),
    path('citizens_appeals_list_json/', views.citizens_appeals_json, name='citizens_appeals_list_json'),
    path('citizens_appeals_rubric_json/', views.citizens_appeals_json, name='citizens_appeals_rubric_json'),
    path('citizens_appeals_executor_json/', views.citizens_appeals_json, name='citizens_appeals_executor_json'),
    path('citizens_appeals_address_json/', views.citizens_appeals_json, name='citizens_appeals_address_json')
]
